package ru.openmes.feature.more

/**
 * Разведка: GET-запросы, прогоняемые подряд в logcat (OpenMES-API) — по docs/college-api/.
 * Только то, что у колледжа отвечает 200 (прогон 2026-09-26); нерабочее убрано.
 */
internal val probes = listOf(
    // Дневник (family/mobile и /api/ej — роутинг переводит на profeducation)
    "api/family/mobile/v1/profile",
    "api/family/mobile/v1/schedule/short?student_id={studentId}&dates={today}",
    "api/family/mobile/v1/schedule/short?student_id={studentId}&dates={monday},{sunday}",
    "api/family/mobile/v1/periods_schedules?student_id={studentId}&from={monthAgo}&to={today}",
    "api/family/mobile/v1/marks?student_id={studentId}&from={monthAgo}&to={today}",
    "api/family/mobile/v1/subject_marks/short?student_id={studentId}",
    "api/family/mobile/v1/subject_marks/short?student_id={studentId}&ceil_after=51",
    "api/family/mobile/v1/final_marks?student_id={studentId}",
    "api/family/mobile/v1/attestation?student_id={studentId}&is_current_year=true&attestation_forms=EXAM&attestation_forms=TEST&attestation_forms=COURSE_WORK&attestation_forms=PRACTICE&attestation_forms=GIA",
    "api/family/mobile/v1/attestation?student_id={studentId}&academic_year_id=14&attestation_forms=EXAM&attestation_forms=TEST&attestation_forms=COURSE_WORK&attestation_forms=PRACTICE&attestation_forms=GIA",
    "api/family/mobile/v1/subjects/list?student_id={studentId}",
    "api/family/mobile/v1/homeworks/short?student_id={studentId}&from={monday}&to={sunday}&sort_column=date&sort_direction=asc",
    "api/family/mobile/v1/homeworks?student_id={studentId}&from={monday}&to={sunday}",
    "api/family/mobile/v1/attendance?student_id={studentId}&from={monthAgo}&to={today}",
    "api/family/mobile/v1/student-card?student_id={studentId}",
    "api/family/mobile/v1/settings?person_ids={personGuid}&name=settings_group_v1",
    "api/ej/core/family/v1/academic_years",
    "api/ej/core/family/v1/training_camp",
    "api/ej/core/family/v1/periods_schedules?student_profile_id={studentId}",
    "api/ej/core/family/v1/aware_journals?student_profile_ids={studentId}&week_from={monday}&week_to={sunday}",
    "api/ej/core/family/v1/nonattendance_reasons",
    "api/ej/core/family/v1/emias_medical_recommendations?student_profile_id={studentId}&start_date={monthAgo}&end_date={today}",
    "api/ej/core/family/v1/emias_medical_recommendations?person_ids={personGuid}",
    "api/ej/plan/family/v1/test_lessons/period?student_profile_id={studentId}&student_person_id={personGuid}&from={monthAgo}&to={today}",
    // Портфолио «МП-бэк»
    "api/profeducation/family/mobile/v1/portfolio/science?personId={personGuid}",
    "api/profeducation/family/mobile/v1/portfolio/sport?personId={personGuid}",
    "api/profeducation/family/mobile/v1/portfolio/culture?personId={personGuid}",
    "api/profeducation/family/mobile/v1/portfolio/v2/culture?personId={personGuid}",
    "api/profeducation/family/mobile/v1/portfolio/creation?personId={personGuid}",
    "api/profeducation/family/mobile/v1/portfolio/civil?personId={personGuid}",
    "api/profeducation/family/mobile/v1/portfolio/profession?personId={personGuid}",
    "api/profeducation/family/mobile/v1/portfolio/settings?personId={personGuid}",
    "api/profeducation/family/mobile/v1/portfolio/interests?personId={personGuid}&entity=head",
    "api/profeducation/family/mobile/v1/portfolio/proforientation/status?personId={personGuid}",
    // Портфолио-сервис
    "api/portfolio/app/persons/{personGuid}/academic/performance/average",
    "api/portfolio/app/persons/{personGuid}/v2/academic-performance/average-mark",
    "api/portfolio/app/persons/{personGuid}/govexams/list",
    "api/portfolio/app/persons/{personGuid}/events/list",
    "api/portfolio/app/persons/{personGuid}/rewards/list?size=100",
    "api/portfolio/app/persons/{personGuid}/diagnostic/independent-rating",
    "api/portfolio/app/persons/{personGuid}/diagnostic/general-rating",
    "api/portfolio/app/persons/{personGuid}/personal-diagnostic-grouped?count=1",
    "api/portfolio/app/persons/{personGuid}/share/list",
    "api/portfolio/app/reference/olympiad/subject?size=100",
    "api/portfolio/app/fos/feedbackLink",
    // Новости (service_id колледжа = 59)
    "api/news/v2/news/users?page=1&per_page=10",
    "api/news/v2/news/users/v2?page=1&per_page=10",
    "api/news/v2/news/main/users?page=1&per_page=10",
    "api/news/v2/news/top",
    "api/news/v2/news/top/recommended",
    "api/news/v2/channels?page=1&per_page=20",
    "api/news/v2/channels/system",
    "api/news/v2/catalogs?catalogue_name=TAGS",
    "api/news/v2/catalogs?catalogue_name=EMOJI&emoji_usage=NEWS",
    "api/news/v2/announcements/user?filter=ALL&service_id=59",
    "api/news/v2/banners/v2?location=HEADER&service_id=59",
    "api/news/v2/stories/user?service_id=59",
    "api/news/v2/stories/favorite/list/v2?service_id=59&page=1&per_page=10",
    // Рейтинг (роутинг переводит на /api/profeducation/rating/v1)
    "api/ej/rating/v1/rank/rankShort?personId={personGuid}&beginDate={monthAgo}&endDate={today}",
    "api/ej/rating/v1/rank/subjects?personId={personGuid}&date={today}",
    "api/ej/rating/v1/rank/class?personId={personGuid}&date={today}",
    // Сервисы
    "api/food/meals/v3/clients/balance?clientIds=[{\"personId\":\"{personGuid}\"}]",
    "api/food/meals/v3/clients/allowed-food-state?clientId={\"personId\":\"{personGuid}\"}",
    "api/food/meals/v3/clients/food-provider?clientId={\"personId\":\"{personGuid}\"}",
    "api/food/meals/v3/menu/buffet?clientId={\"personId\":\"{personGuid}\"}&from={today}&to={today}&withFoodbox=in",
    "api/food/meals/v3/menu/complexes?clientId={\"personId\":\"{personGuid}\"}&from={monday}&to={sunday}&withPreorder=in",
    "api/food/meals/v3/menu/prohibitions?clientId={\"personId\":\"{personGuid}\"}",
    "api/food/meals/v3/transactions?clientId={\"personId\":\"{personGuid}\"}&from={monthAgo}&to={today}&limit=50&offset=0",
    "api/food/meals/v3/orders?clientId={\"personId\":\"{personGuid}\"}&from={monthAgo}&to={today}&limit=50&offset=0",
    "api/food/meals/v3/orders/rules?clientId={\"personId\":\"{personGuid}\"}&from={monday}&to={sunday}",
    "api/food/meals/v3/orders/preorder/summary?clientId={\"personId\":\"{personGuid}\"}",
    "api/instantmessages/v1/feed?page=1&npp=20",
    "api/instantmessages/v1/feed?page=1&npp=20&filter={\"child_id\":\"{personGuid}\"}",
    "api/instantmessages/v1/count_new",
    "api/instantmessages/v1/count_new_important",
    "api/notifications/usersettings/v1/user/setting?mail_target_id=6",
    "api/usersettings/v1?name=settings_group_v1",
    "api/usersettings/v1?name=UC_TTC_CARD_BALANCE",
    "api/usersettings/v1?name=favoriteServices",
    "api/pass/entrances/v1/status?personId={personGuid}",
    "api/certificates/family/v1/certificates/statuses",
    "api/avatarmanagement/v1/{personGuid}",
    "api/consents/consents?person_ids={personGuid}",
    "api/consents/permission_status?person_ids={personGuid}",
    "api/aupd/v2/external-partners/check-for-vk-user?person_id={personGuid}",
    "api/aupd/v2/external-partners/check-for-max-user?person_id={personGuid}",
    "api/aupd/v1/user/childrens?person_id={personGuid}",
    "api/nsi/dictionaries/v1/credit_organizations",
    "api/nsi/dictionaries/v1/GAMIFICATION_PARTNER",
    "api/nsi/dictionaries/v1/family",
    "api/fos/v1/url",
)
